# Generated by Django 3.0.4 on 2020-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='item_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
