# Generated by Django 3.0.4 on 2020-04-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200417_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_Quantity',
            new_name='item_quantity',
        ),
    ]
