# Generated by Django 3.0.4 on 2020-05-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200417_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_id',
        ),
    ]
