# Generated by Django 3.0.4 on 2020-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200506_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='address2',
            field=models.CharField(max_length=100),
        ),
    ]
