# Generated by Django 3.0.4 on 2020-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200507_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderform',
            old_name='city',
            new_name='state',
        ),
    ]
